# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/g620_a2/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/g620_a2/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:system/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    vendor/huawei/g620_a2/proprietary/etc/sound_param/h891l/Global_cal.acdb:system/etc/sound_param/h891l/Global_cal.acdb \
    vendor/huawei/g620_a2/proprietary/etc/sound_param/h891l/General_cal.acdb:system/etc/sound_param/h891l/General_cal.acdb \
    vendor/huawei/g620_a2/proprietary/etc/sound_param/h891l/Hdmi_cal.acdb:system/etc/sound_param/h891l/Hdmi_cal.acdb \
    vendor/huawei/g620_a2/proprietary/etc/sound_param/h891l/Headset_cal.acdb:system/etc/sound_param/h891l/Headset_cal.acdb \
    vendor/huawei/g620_a2/proprietary/etc/sound_param/h891l/Speaker_cal.acdb:system/etc/sound_param/h891l/Speaker_cal.acdb \
    vendor/huawei/g620_a2/proprietary/etc/sound_param/h891l/Handset_cal.acdb:system/etc/sound_param/h891l/Handset_cal.acdb \
    vendor/huawei/g620_a2/proprietary/etc/sound_param/h891l/Bluetooth_cal.acdb:system/etc/sound_param/h891l/Bluetooth_cal.acdb \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/huawei/g620_a2/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/huawei/g620_a2/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/huawei/g620_a2/proprietary/bin/charger_monitor:system/bin/charger_monitor \
    vendor/huawei/g620_a2/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/huawei/g620_a2/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/huawei/g620_a2/proprietary/etc/izat.conf:system/etc/izat.conf \
    vendor/huawei/g620_a2/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/huawei/g620_a2/proprietary/etc/quipc.conf:system/etc/quipc.conf \
    vendor/huawei/g620_a2/proprietary/etc/sap.conf:system/etc/sap.conf \
    vendor/huawei/g620_a2/proprietary/etc/xtra_root_cert.pem:system/etc/xtra_root_cert.pem \
    vendor/huawei/g620_a2/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf \
    vendor/huawei/g620_a2/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/huawei/g620_a2/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
    vendor/huawei/g620_a2/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/huawei/g620_a2/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/huawei/g620_a2/proprietary/lib/libOmxVdecHevc.so:system/lib/libOmxVdecHevc.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmQTA.so:system/vendor/lib/libmmQTA.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    vendor/huawei/g620_a2/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    vendor/huawei/g620_a2/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/huawei/g620_a2/proprietary/bin/qcom-system-daemon:system/bin/qcom-system-daemon \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    vendor/huawei/g620_a2/proprietary/bin/libqmi_oem_main:system/bin/libqmi_oem_main \
    vendor/huawei/g620_a2/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/huawei/g620_a2/proprietary/bin/oeminfo_server:system/bin/oeminfo_server \
    vendor/huawei/g620_a2/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/g620_a2/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/huawei/g620_a2/proprietary/bin/rmt_oeminfo:system/bin/rmt_oeminfo \
    vendor/huawei/g620_a2/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/huawei/g620_a2/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/huawei/g620_a2/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/huawei/g620_a2/proprietary/lib/liboeminfo.so:system/lib/liboeminfo.so \
    vendor/huawei/g620_a2/proprietary/lib/libqmi_nv_api.so:system/lib/libqmi_nv_api.so \
    vendor/huawei/g620_a2/proprietary/lib/libqmi_oem_api.so:system/lib/libqmi_oem_api.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/huawei/g620_a2/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/huawei/g620_a2/proprietary/vendor/lib/hw/sensors.msm8226.so:system/vendor/lib/hw/sensors.msm8226.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/huawei/g620_a2/proprietary/lib/liboeminfo_oem_api.so:system/lib/liboeminfo_oem_api.so \
    vendor/huawei/g620_a2/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libAKM8963.so:system/vendor/lib/libAKM8963.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libAKM8975.so:system/vendor/lib/libAKM8975.so \
    vendor/huawei/g620_a2/proprietary/etc/firmware/h891L_eely_fw.img:system/etc/firmware/h891L_eely_fw.img \
    vendor/huawei/g620_a2/proprietary/etc/firmware/h891L_ofilm_fw.img:system/etc/firmware/h891L_ofilm_fw.img \
    vendor/huawei/g620_a2/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/huawei/g620_a2/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/huawei/g620_a2/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/huawei/g620_a2/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/huawei/g620_a2/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/huawei/g620_a2/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/huawei/g620_a2/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/huawei/g620_a2/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/huawei/g620_a2/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/huawei/g620_a2/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt
