# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8220/extract-files.sh - DO NOT EDIT

# All the blobs necessary for u8220
PRODUCT_COPY_FILES += \
    vendor/huawei/u8220/proprietary/akmd2:system/bin/akmd2 \
    vendor/huawei/u8220/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/huawei/u8220/proprietary/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \
    vendor/huawei/u8220/proprietary/libGLES_qcom.so:system/lib/egl/libGLES_qcom.so \
    vendor/huawei/u8220/proprietary/libril-qc-1.so:/system/lib/libril-qc-1.so \
    vendor/huawei/u8220/proprietary/liboncrpc.so:/system/lib/liboncrpc.so \
    vendor/huawei/u8220/proprietary/libdsm.so:/system/lib/libdsm.so \
    vendor/huawei/u8220/proprietary/libqueue.so:/system/lib/libqueue.so \
    vendor/huawei/u8220/proprietary/libcm.so:/system/lib/libcm.so \
    vendor/huawei/u8220/proprietary/libdiag.so:/system/lib/libdiag.so \
    vendor/huawei/u8220/proprietary/libmmgsdilib.so:/system/lib/libmmgsdilib.so \
    vendor/huawei/u8220/proprietary/libgsdi_exp.so:/system/lib/libgsdi_exp.so \
    vendor/huawei/u8220/proprietary/libgstk_exp.so:/system/lib/libgstk_exp.so \
    vendor/huawei/u8220/proprietary/libwms.so:/system/lib/libwms.so \
    vendor/huawei/u8220/proprietary/libnv.so:/system/lib/libnv.so \
    vendor/huawei/u8220/proprietary/libwmsts.so:/system/lib/libwmsts.so \
    vendor/huawei/u8220/proprietary/libpbmlib.so:/system/lib/libpbmlib.so \
    vendor/huawei/u8220/proprietary/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8220/proprietary/libdss.so:/system/lib/libdss.so \
    vendor/huawei/u8220/proprietary/libqmi.so:/system/lib/libqmi.so \
    vendor/huawei/u8220/proprietary/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/u8220/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/huawei/u8220/proprietary/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/u8220/proprietary/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8220/proprietary/libmmcamera.so:system/lib/libmmcamera.so \
    vendor/huawei/u8220/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8220/proprietary/libmm-qcamera-tgt.so:system/lib/libmm-qcamera-tgt.so \
    vendor/huawei/u8220/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/u8220/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/huawei/u8220/proprietary/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    vendor/huawei/u8220/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/huawei/u8220/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/huawei/u8220/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/huawei/u8220/proprietary/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/huawei/u8220/proprietary/libomx_wmadec_sharedlibrary.so:system/lib/libomx_wmadec_sharedlibrary.so \
    vendor/huawei/u8220/proprietary/libomx_wmvdec_sharedlibrary.so:system/lib/libomx_wmvdec_sharedlibrary.so \
    vendor/huawei/u8220/proprietary/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/huawei/u8220/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init
