# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/mt2/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/mt2/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/huawei/mt2/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/huawei/mt2/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/huawei/mt2/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    vendor/huawei/mt2/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/huawei/mt2/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/huawei/mt2/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/huawei/mt2/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/huawei/mt2/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/huawei/mt2/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/huawei/mt2/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/huawei/mt2/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/huawei/mt2/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/huawei/mt2/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/huawei/mt2/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/huawei/mt2/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
    vendor/huawei/mt2/proprietary/app/com.qualcomm.location.apk:system/app/com.qualcomm.location.apk \
    vendor/huawei/mt2/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
    vendor/huawei/mt2/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/huawei/mt2/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/huawei/mt2/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/huawei/mt2/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/huawei/mt2/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/huawei/mt2/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/huawei/mt2/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/huawei/mt2/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/huawei/mt2/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/huawei/mt2/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/huawei/mt2/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/huawei/mt2/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/huawei/mt2/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/huawei/mt2/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/huawei/mt2/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/huawei/mt2/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/huawei/mt2/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/huawei/mt2/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/huawei/mt2/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/huawei/mt2/proprietary/app/qcrilmsgtunnel.apk:system/app/qcrilmsgtunnel.apk \
    vendor/huawei/mt2/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/huawei/mt2/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/mt2/proprietary/bin/radish:system/bin/radish \
    vendor/huawei/mt2/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/huawei/mt2/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/huawei/mt2/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/huawei/mt2/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    vendor/huawei/mt2/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/huawei/mt2/proprietary/lib/libqmi_nv_api.so:system/lib/libqmi_nv_api.so \
    vendor/huawei/mt2/proprietary/lib/libqmi_oem_api.so:system/lib/libqmi_oem_api.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/huawei/mt2/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/huawei/mt2/proprietary/vendor/lib/hw/sensors.msm8928.so:system/vendor/lib/hw/sensors.msm8928.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/huawei/mt2/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/huawei/mt2/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/huawei/mt2/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/huawei/mt2/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/huawei/mt2/proprietary/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
    vendor/huawei/mt2/proprietary/bin/hvdcp:system/bin/hvdcp

PRODUCT_COPY_FILES += \
    vendor/huawei/mt2/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/huawei/mt2/proprietary/bin/gpsone_daemon:system/bin/gpsone_daemon \
    vendor/huawei/mt2/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    vendor/huawei/mt2/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
    vendor/huawei/mt2/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
    vendor/huawei/mt2/proprietary/bin/qcom-system-daemon:system/bin/qcom-system-daemon \
    vendor/huawei/mt2/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/huawei/mt2/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/huawei/mt2/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so

PRODUCT_COPY_FILES += \
    vendor/huawei/mt2/proprietary/etc/init.ath3k.bt.sh:system/etc/init.ath3k.bt.sh \
    vendor/huawei/mt2/proprietary/etc/init.crda.sh:system/etc/init.crda.sh \
    vendor/huawei/mt2/proprietary/etc/init.qcom.audio.sh:system/etc/init.qcom.audio.sh \
    vendor/huawei/mt2/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/huawei/mt2/proprietary/etc/init.qcom.coex.sh:system/etc/init.qcom.coex.sh \
    vendor/huawei/mt2/proprietary/etc/init.qcom.efs.sync.sh:system/etc/init.qcom.efs.sync.sh \
    vendor/huawei/mt2/proprietary/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
    vendor/huawei/mt2/proprietary/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \
    vendor/huawei/mt2/proprietary/etc/init.qcom.sdio.sh:system/etc/init.qcom.sdio.sh \
    vendor/huawei/mt2/proprietary/etc/init.qcom.wifi.sh:system/etc/init.qcom.wifi.sh \
    vendor/huawei/mt2/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/huawei/mt2/proprietary/etc/thermal-engine-8226.conf:system/etc/thermal-engine-8226.conf

PRODUCT_COPY_FILES += \
    vendor/huawei/mt2/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/huawei/mt2/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/huawei/mt2/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/huawei/mt2/proprietary/etc/firmware/cyttsp4_fw_g6.bin:system/etc/firmware/cyttsp4_fw_g6.bin \
    vendor/huawei/mt2/proprietary/etc/firmware/cyttsp4_fw_g750.bin:system/etc/firmware/cyttsp4_fw_g750.bin \
    vendor/huawei/mt2/proprietary/etc/firmware/cyttsp4_fw_mainboard.bin:system/etc/firmware/cyttsp4_fw_mainboard.bin \
    vendor/huawei/mt2/proprietary/etc/firmware/cyttsp4_fw_mate2.bin:system/etc/firmware/cyttsp4_fw_mate2.bin \
    vendor/huawei/mt2/proprietary/etc/firmware/g620L_junda_fw.img:system/etc/firmware/g620L_junda_fw.img \
    vendor/huawei/mt2/proprietary/etc/firmware/g620L_ofilm_fw.img:system/etc/firmware/g620L_ofilm_fw.img \
    vendor/huawei/mt2/proprietary/etc/firmware/g660L_ofilm_fw.img:system/etc/firmware/g660L_ofilm_fw.img \
    vendor/huawei/mt2/proprietary/etc/firmware/g660L_truly_fw.img:system/etc/firmware/g660L_truly_fw.img \
    vendor/huawei/mt2/proprietary/etc/firmware/g730L_junda_fw.img:system/etc/firmware/g730L_junda_fw.img \
    vendor/huawei/mt2/proprietary/etc/firmware/g730L_ofilm_fw.img:system/etc/firmware/g730L_ofilm_fw.img

PRODUCT_COPY_FILES += \
    vendor/huawei/mt2/proprietary/lib/hw/camera.msm8928.so:system/lib/hw/camera.msm8928.so \
    vendor/huawei/mt2/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/huawei/mt2/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/huawei/mt2/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so

PRODUCT_COPY_FILES += \
    vendor/huawei/mt2/proprietary/etc/gps.conf:system/etc/gps.conf

