# Copyright (C) 2010 The AndroidOpen Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8160/extract-files.sh - DO NOT EDIT

# All the blobs necessary for U8160
PRODUCT_COPY_FILES += \
    vendor/huawei/u8160/proprietary/etc/01_qc.cfg:system/etc/01_qc.cfg \
    vendor/huawei/u8160/proprietary/etc/AudioFilterU8160.csv:system/etc/AudioFilterU8160.csv \
    vendor/huawei/u8160/proprietary/etc/pvplayer.cfg:system/etc/pvplayer.cfg \
    vendor/huawei/u8160/proprietary/etc/bluetooth/BCM4329.hcd:system/etc/bluetooth/BCM4329.hcd

PRODUCT_COPY_FILES += \
    vendor/huawei/u8160/proprietary/bin/akmd2:system/bin/akmd2 \
    vendor/huawei/u8160/proprietary/bin/akmd8962:system/bin/akmd8962 \
    vendor/huawei/u8160/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/huawei/u8160/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/huawei/u8160/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8160/proprietary/bin/rild:system/bin/rild

PRODUCT_COPY_FILES += \
    vendor/huawei/u8160/proprietary/lib/hw/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so \
    vendor/huawei/u8160/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so

PRODUCT_COPY_FILES += \
    vendor/huawei/u8160/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/huawei/u8160/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/huawei/u8160/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/huawei/u8160/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/u8160/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8160/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/huawei/u8160/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/u8160/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/u8160/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/u8160/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/u8160/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/huawei/u8160/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    vendor/huawei/u8160/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/u8160/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/u8160/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8160/proprietary/lib/libmmprocess.so:system/lib/libmmprocess.so \
    vendor/huawei/u8160/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/u8160/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/huawei/u8160/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/huawei/u8160/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/huawei/u8160/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/huawei/u8160/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/huawei/u8160/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8160/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/u8160/proprietary/lib/libqcamera.so:system/lib/libqcamera.so \
    vendor/huawei/u8160/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/u8160/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/u8160/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/huawei/u8160/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/u8160/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8160/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/u8160/proprietary/lib/libwmsts.so:system/lib/libwmsts.so

